on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Comment Stories Coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Calc Coverage
        id: calc-coverage
        run: echo "::set-output name=coverage::$(node coverage.js ".*.vue" ".*.stories.ts|js" ./src)"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello! ${{ steps.calc-coverage.outputs.coverage }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
